apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lsweep-agent-proxy.fullname" . }}
  labels:
    {{- include "lsweep-agent-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lsweep-agent-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lsweep-agent-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "DEBUG"
              value: {{ .Values.applicationSettings.debug | quote}}
            - name: "LISTEN_HOSTNAME"
              value: {{ .Values.applicationSettings.publicDomain | quote}}
            - name: "PUBLIC_PORT"
              value: {{ .Values.applicationSettings.publicPort | quote }}
            - name: LSSERVER_HOST
              value: {{ .Values.applicationSettings.lansweeper.server | quote }}
            - name: LSSERVER_PORT
              value: {{ .Values.applicationSettings.lansweeper.port | quote }}
            - name: LSSERVER_CERT
              value: {{ .Values.applicationSettings.lansweeper.certificate | quote }}
            - name: LSSERVER_IGNORE_CERT
              value: {{ .Values.applicationSettings.lansweeper.ignoreCertErrors | quote }}
          ports:
            - name: http
              containerPort: 8011
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ctstatus
              port: http
          readinessProbe:
            httpGet:
              path: /ctstatus
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
