# How many replicas of the agent proxy to run in the cluster
replicaCount: 1

image:
  repository: cloudyne.azurecr.io/lsweep/agent-proxy:latest
  pullPolicy: IfNotPresent
  
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

#


applicationSettings:
  # Activate debug logging
  debug: "false"
  
  # The publicDomain should be the external DNS name the agent proxy is reachable on.
  # this is normally the same as the host in the ingress configuration.
  # If your ingress listens on a non-standard port, change the publicPort below
  publicDomain: "lsagentproxy.example.com"
  publicPort: "443"

  # Connection settings for the LANSweeper Server
  lansweeper:
    # The DNS name or IP that the LANSweeper server is listening on
    server: "lansweeper.example.com"
    
    # This is the agent listen port, not the main webserver
    port: "9524"

    # Certificate for verification (not implemented)
    certificate: ""

    # Ignore certificate errors
    ignoreCertErrors: "true"

service:
  type: ClusterIP
  port: 8011


# podAnnotations: {}

# podSecurityContext: {}
#   # fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  runasNonRoot: true
  runAsUser: 1000


# Configure ingress resource to add SSL Certificate
ingress:
  enabled: false
  className: ""
  annotations: {}
    # Use existing nginx ingress controller
    # kubernetes.io/ingress.class: nginx
    # Get SSL Certificate via ACME/LE
    # kubernetes.io/tls-acme: "true"
  # The external host name to access the proxy
  hosts:
    - host: lsagentproxy.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: manual-tls-secret
  #    hosts:
  #      - lsagentproxy.example.com


# By default, resources are constricted since the image is small and light
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
