name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    env:
      VERSION_NUMBER: "0.2.3"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to repository cloudyne.azurecr.io
        uses: docker/login-action@v2
        with:
          registry: cloudyne.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image and push to cloudyne.azurecr.io
        uses: docker/build-push-action@v2
        with:
          context: ./lsweep-agent-proxy
          push: true
          tags: |
            cloudyne.azurecr.io/lsweep/agent-proxy:latest
            cloudyne.azurecr.io/lsweep/agent-proxy:${{ env.VERSION_NUMBER }}
      
      - name: Publish to Docker Hub
        run: |
          docker tag cloudyne.azurecr.io/lsweep/agent-proxy:latest cloudyne/lsweep-agent-proxy:latest
          docker tag cloudyne.azurecr.io/lsweep/agent-proxy:${{ env.VERSION_NUMBER }} cloudyne/lsweep-agent-proxy:${{ env.VERSION_NUMBER }}
          docker push cloudyne/lsweep-agent-proxy:latest
          docker push cloudyne/lsweep-agent-proxy:${{ env.VERSION_NUMBER }}

      - name: Output digest
        run: echo ${{ steps.buildx.outputs.digest }}